// Code generated by MockGen. DO NOT EDIT.
// Source: equipment/phone.go

// Package equipment is a generated GoMock package.
package equipment

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPhone is a mock of Phone interface.
type MockPhone struct {
	ctrl     *gomock.Controller
	recorder *MockPhoneMockRecorder
}

// MockPhoneMockRecorder is the mock recorder for MockPhone.
type MockPhoneMockRecorder struct {
	mock *MockPhone
}

// NewMockPhone creates a new mock instance.
func NewMockPhone(ctrl *gomock.Controller) *MockPhone {
	mock := &MockPhone{ctrl: ctrl}
	mock.recorder = &MockPhoneMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhone) EXPECT() *MockPhoneMockRecorder {
	return m.recorder
}

// WangZhe mocks base method.
func (m *MockPhone) WangZhe() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WangZhe")
	ret0, _ := ret[0].(bool)
	return ret0
}

// WangZhe indicates an expected call of WangZhe.
func (mr *MockPhoneMockRecorder) WangZhe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WangZhe", reflect.TypeOf((*MockPhone)(nil).WangZhe))
}

// WeiXin mocks base method.
func (m *MockPhone) WeiXin() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WeiXin")
	ret0, _ := ret[0].(bool)
	return ret0
}

// WeiXin indicates an expected call of WeiXin.
func (mr *MockPhoneMockRecorder) WeiXin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WeiXin", reflect.TypeOf((*MockPhone)(nil).WeiXin))
}

// ZhiHu mocks base method.
func (m *MockPhone) ZhiHu() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ZhiHu")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ZhiHu indicates an expected call of ZhiHu.
func (mr *MockPhoneMockRecorder) ZhiHu() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ZhiHu", reflect.TypeOf((*MockPhone)(nil).ZhiHu))
}
